-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS studyforge.alembic_version
(
    version_num character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE IF NOT EXISTS studyforge.documents
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    file_size_bytes integer NOT NULL,
    file_content bytea NOT NULL,
    extracted_text character varying COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT documents_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS studyforge.quiz_attempts
(
    id uuid NOT NULL,
    quiz_id uuid NOT NULL,
    user_id uuid NOT NULL,
    started_at timestamp without time zone NOT NULL,
    completed_at timestamp without time zone,
    score double precision,
    correct_answers jsonb NOT NULL,
    user_answers jsonb NOT NULL,
    quiz_snapshot jsonb,
    study_space_snapshot jsonb,
    quiz_title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    quiz_state character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT quiz_attempts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS studyforge.quizzes
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    difficulty_level integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    questions jsonb NOT NULL,
    study_space_id uuid NOT NULL,
    source_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    source_document_id uuid,
    source_summary_id uuid,
    source_names jsonb,
    source_metadata jsonb,
    CONSTRAINT quizzes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS studyforge.study_space_documents
(
    study_space_id uuid NOT NULL,
    document_id uuid NOT NULL,
    CONSTRAINT study_space_documents_pkey PRIMARY KEY (study_space_id, document_id)
);

CREATE TABLE IF NOT EXISTS studyforge.study_spaces
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default",
    color character varying(7) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT study_spaces_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS studyforge.summaries
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content jsonb NOT NULL,
    expertise_level character varying(20) COLLATE pg_catalog."default" NOT NULL,
    topics jsonb NOT NULL,
    key_concepts jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    document_id uuid,
    study_space_id uuid NOT NULL,
    document_state character varying(50) COLLATE pg_catalog."default" NOT NULL,
    source_document_title character varying(255) COLLATE pg_catalog."default",
    source_document_filename character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT summaries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS studyforge.users
(
    id uuid NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    hashed_password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    storage_quota_bytes bigint NOT NULL,
    storage_used_bytes bigint NOT NULL,
    max_documents_per_summary integer NOT NULL,
    max_file_size_bytes bigint NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS studyforge.documents
    ADD CONSTRAINT fk_documents_user_id_users FOREIGN KEY (user_id)
    REFERENCES studyforge.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_studyforge_documents_user_id
    ON studyforge.documents(user_id);


ALTER TABLE IF EXISTS studyforge.quiz_attempts
    ADD CONSTRAINT fk_quiz_attempts_quiz_id_quizzes FOREIGN KEY (quiz_id)
    REFERENCES studyforge.quizzes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_studyforge_quiz_attempts_quiz_id
    ON studyforge.quiz_attempts(quiz_id);


ALTER TABLE IF EXISTS studyforge.quiz_attempts
    ADD CONSTRAINT fk_quiz_attempts_user_id_users FOREIGN KEY (user_id)
    REFERENCES studyforge.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_studyforge_quiz_attempts_user_id
    ON studyforge.quiz_attempts(user_id);


ALTER TABLE IF EXISTS studyforge.quizzes
    ADD CONSTRAINT fk_quizzes_source_document_id_documents FOREIGN KEY (source_document_id)
    REFERENCES studyforge.documents (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_studyforge_quizzes_source_document_id
    ON studyforge.quizzes(source_document_id);


ALTER TABLE IF EXISTS studyforge.quizzes
    ADD CONSTRAINT fk_quizzes_source_summary_id_summaries FOREIGN KEY (source_summary_id)
    REFERENCES studyforge.summaries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_studyforge_quizzes_source_summary_id
    ON studyforge.quizzes(source_summary_id);


ALTER TABLE IF EXISTS studyforge.quizzes
    ADD CONSTRAINT fk_quizzes_study_space_id_study_spaces FOREIGN KEY (study_space_id)
    REFERENCES studyforge.study_spaces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_studyforge_quizzes_study_space_id
    ON studyforge.quizzes(study_space_id);


ALTER TABLE IF EXISTS studyforge.quizzes
    ADD CONSTRAINT fk_quizzes_user_id_users FOREIGN KEY (user_id)
    REFERENCES studyforge.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_studyforge_quizzes_user_id
    ON studyforge.quizzes(user_id);


ALTER TABLE IF EXISTS studyforge.study_space_documents
    ADD CONSTRAINT fk_study_space_documents_document_id_documents FOREIGN KEY (document_id)
    REFERENCES studyforge.documents (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS studyforge.study_space_documents
    ADD CONSTRAINT fk_study_space_documents_study_space_id_study_spaces FOREIGN KEY (study_space_id)
    REFERENCES studyforge.study_spaces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS studyforge.study_spaces
    ADD CONSTRAINT fk_study_spaces_user_id_users FOREIGN KEY (user_id)
    REFERENCES studyforge.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_studyforge_study_spaces_user_id
    ON studyforge.study_spaces(user_id);


ALTER TABLE IF EXISTS studyforge.summaries
    ADD CONSTRAINT fk_summaries_document_id_documents FOREIGN KEY (document_id)
    REFERENCES studyforge.documents (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_studyforge_summaries_document_id
    ON studyforge.summaries(document_id);


ALTER TABLE IF EXISTS studyforge.summaries
    ADD CONSTRAINT fk_summaries_study_space_id_study_spaces FOREIGN KEY (study_space_id)
    REFERENCES studyforge.study_spaces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_studyforge_summaries_study_space_id
    ON studyforge.summaries(study_space_id);


ALTER TABLE IF EXISTS studyforge.summaries
    ADD CONSTRAINT fk_summaries_user_id_users FOREIGN KEY (user_id)
    REFERENCES studyforge.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_studyforge_summaries_user_id
    ON studyforge.summaries(user_id);

END;